### ISSUE TITLE
Iron router -> flow-router reload loop question

### ISSUE THREAD

**Issue by daveeel** [meteorhacks/flow-router#178]
I tried to migrate a project from Iron router to flow router, the app loads fine at "/", however whenever I click to any other route, the app starts to reload, reload, reload ... forever.

I followed the doc to migrate ... everything latest version

When I roll back to Iron Router, no such issue.

What could be the possible reason(s)? 
We used Polymer 1.0, would there be possible conflict?

**Comment by arunoda** [comment]
It's very hard to answer questions like this. We need sample code to replicate ourselves. I personally didn't tested with polymer. But I see a thread on Meteor Forums about this.

May be try that.

**Comment by daveeel** [comment]
@arunoda , do you mind if I zip and send the test project with the issue to you?

**Comment by arunoda** [comment]
yep sure. Send me to my email. arunoda [at] meteorhacks.com.
Make sure to remove `.meteor/local` directory.

**Comment by arunoda** [comment]
Try the latest version as I fixed a potential issue.

**Comment by daveeel** [comment]
Just upgraded from 1.16.2 to 1.16.3 and the reload loop seems to be fixed. However one related issue still persist. The app complains no route for /account, however the route will load as expected after Polymer's WebComponentsReady is fired. See attached screen shot. Shall send you the project zip anyway. Thanks for the quick fix :+1: 

![screen shot 2015-06-26 at 4 41 21 pm](https://cloud.githubusercontent.com/assets/163661/8373819/ae9f792c-1c22-11e5-819d-972b5971c5c1.png)

**Comment by arunoda** [comment]
Okay. That's iron-router complaining :)
Not us.

**Comment by daveeel** [comment]
Oh I see. I'm too quick and have already sent you the email.

But then how do we avoid this situation? 
Because other packages like useraccounts:core depends on iron:router

**Comment by arunoda** [comment]
There is user-accounts flow-router version. Try to use it.

**Comment by daveeel** [comment]
Great! shall try it out.
